servers:
  - name: Erebus
    address: http://erebus:9100
  - name: Thanatos
    address: http://thanatos:9100
  - name: Zelus
    address: http://zelus:9100
  - name: Orpheus
    address: http://orpheus:9100
#  - name: Hades
#    address: http://hades:9100

dashboard:
  host: 0.0.0.0
  port: 5000
  debug: true

metrics_port: 8000

redis:
  host: 10.42.0.109
  port: 6379
  db: 0
