servers:
  - name: ServerOne
    address: http://ServerOne:9100
  - name: ServerTwo
    address: http://ServerTwo:9100

dashboard:
  host: 0.0.0.0
  port: 5000
  debug: true

metrics_port: 8000

redis:
  host: localhost
  port: 6379
  db: 0