name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      valkey:
        image: docker.io/valkey/valkey:latest
        options: >-
          --health-cmd "redis-cli ping | grep PONG"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Copy config-example.yaml to config.yaml
      run: cp config-example.yaml config.yaml
    - name: Modify config.yaml for CI
      run: |
        sed -i 's/localhost/valkey/' config.yaml
        sed -i 's/ServerOne/localhost/' config.yaml
    - name: Install dependencies
      run: |
        apt update && apt install redis-cli
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for Valkey to be available
      run: |
        for i in {1..10}; do
          if redis-cli -h valkey ping; then
            break
          fi
          echo "Waiting for Valkey to be available..."
          sleep 5
        done
    - name: Run tests
      env:
        VALKEY_HOST: valkey
        VALKEY_PORT: 6379  
      run: |
        python -m unittest discover tests
      
