name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      valkey:
        image: docker.io/valkey/valkey:latest
        options: >-
          --health-cmd "valkey-cli ping | grep PONG"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Copy config-example.yaml to config.yaml
      run: cp config-example.yaml config.yaml
    - name: Modify config.yaml for CI
      run: |
        sed -i "s/localhost/${VALKEY_HOST}/" config.yaml
        sed -i "s/ServerOne/localhost/" config.yaml
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y redis-tools
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for Valkey to be available
      run: |
        sleep 30
        for i in {1..10}; do
          if valkey-cli -h ${VALKEY_HOST} ping | grep PONG; then
            break
          fi
          echo "Waiting for Valkey to be available..."
          sleep 5
        done
    - name: Verify Valkey container is running
      run: docker ps
    - name: Run tests
      run: |
        python -m unittest discover tests
